### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by WtfJoke** [sjfricke/UniTooth#8]
I am interested in your project but dont find any guidance how I start? Or any working demo?

Do you have anything where I can start?

**Comment by sjfricke** [comment]
Hey,

So that is something I have wanted to put together and just have had to put off with school. I can put something together later today. Thanks for the notice/interest

**Comment by bboettcher3** [comment]
@WtfJoke Do you still have interest in working with our plugin? I'm not sure if @sjfricke ended up finding time to put together our demo for you, but I'd be willing to help out if there is still interest,

**Comment by WtfJoke** [comment]
Thanks for your offer @bboettcher3, however our project is finished in the meantime, so we dont need it anymore.  You can close this issue if you like or leave it as a reminder :)
